tests: build.zig example.zig
	zig build test

fmt-check: build.zig example.zig
	zig fmt --check build.zig
	zig fmt --check example.zig

fmt: build.zig example.zig
	zig fmt build.zig
	zig fmt example.zig